In [1]:
import pandas as pd

In [52]:
data = pd.read_csv('glassdoor_jobs.csv')
data

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,Data Scientist,$70K-$116K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
1,Data Scientist,$83K-$135K (Glassdoor est.),"Data Scientist, Risk (4+ years of experience)\...",4.6,Turo\n4.6,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2009,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,-1
2,Data Scientist,-1,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
3,Project Manager/Senior Scientist,-1,Project Manager/Senior Scientist\n\nBoyle Asso...,-1.0,"Boyle Associates, a subsidiary of CEA","Portland, ME",-1,-1,-1,-1,-1,-1,-1,-1
4,Data Scientist,$75K-$131K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,"Senior Data Scientist, Product Development",$104K-$140K(Employer est.),Every immune system has a story to tell the ke...,4.0,Adaptive Biotechnologies\n4.0,"Seattle, WA","Seattle, WA",201 to 500 employees,2009,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1
996,"Senior Scientist, Analytical Sciences",$110K-$201K (Glassdoor est.),Forma Therapeutics is focused on the discovery...,4.0,FORMA THERAPEUTICS\n4.0,"Watertown, MA","Watertown, MA",51 to 200 employees,2008,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10 to $25 million (USD),-1
997,"Sr. Research Associate/ Scientist, NGS prep & ...",-1,We are seeking a Sr. Research Associate/Scient...,4.4,"Homology Medicines, Inc.\n4.4","New Bedford, MA","Bedford, MA",51 to 200 employees,-1,Company - Public,-1,-1,Unknown / Non-Applicable,-1
998,Data Analyst - Unilever Prestige,$51K-$55K (Glassdoor est.),Data Analyst - Unilever Prestige\nJob Code\n\n...,3.8,Dermalogica\n3.8,"Carson, CA","Carson, CA",201 to 500 employees,1986,Subsidiary or Business Segment,Consumer Products Manufacturing,Manufacturing,$100 to $500 million (USD),"IMAGE Skincare, Aveda, Kiehl's"
999,IT Data Engineer Associate,$98K-$180K (Glassdoor est.),**We are still hiring and interviewing for thi...,4.5,Global Atlantic Financial Group\n4.5,"New York, NY","New York, NY",1001 to 5000 employees,2004,Company - Private,Insurance Carriers,Insurance,Unknown / Non-Applicable,-1

## salary parsing

In [53]:
df = data.copy()
df['hourly'] = df['Salary Estimate'].apply(lambda x: 1 if 'per hour' in x.lower() else 0)
df['employer_provided'] = df['Salary Estimate'].apply(lambda x: 1 if 'employer provided salary:' in x.lower() else 0)
df

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly,employer_provided
0,Data Scientist,$70K-$116K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,0,0
1,Data Scientist,$83K-$135K (Glassdoor est.),"Data Scientist, Risk (4+ years of experience)\...",4.6,Turo\n4.6,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2009,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,-1,0,0
2,Data Scientist,-1,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",0,0
3,Project Manager/Senior Scientist,-1,Project Manager/Senior Scientist\n\nBoyle Asso...,-1.0,"Boyle Associates, a subsidiary of CEA","Portland, ME",-1,-1,-1,-1,-1,-1,-1,-1,0,0
4,Data Scientist,$75K-$131K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,"Senior Data Scientist, Product Development",$104K-$140K(Employer est.),Every immune system has a story to tell the ke...,4.0,Adaptive Biotechnologies\n4.0,"Seattle, WA","Seattle, WA",201 to 500 employees,2009,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1,0,0
996,"Senior Scientist, Analytical Sciences",$110K-$201K (Glassdoor est.),Forma Therapeutics is focused on the discovery...,4.0,FORMA THERAPEUTICS\n4.0,"Watertown, MA","Watertown, MA",51 to 200 employees,2008,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10 to $25 million (USD),-1,0,0
997,"Sr. Research Associate/ Scientist, NGS prep & ...",-1,We are seeking a Sr. Research Associate/Scient...,4.4,"Homology Medicines, Inc.\n4.4","New Bedford, MA","Bedford, MA",51 to 200 employees,-1,Company - Public,-1,-1,Unknown / Non-Applicable,-1,0,0
998,Data Analyst - Unilever Prestige,$51K-$55K (Glassdoor est.),Data Analyst - Unilever Prestige\nJob Code\n\n...,3.8,Dermalogica\n3.8,"Carson, CA","Carson, CA",201 to 500 employees,1986,Subsidiary or Business Segment,Consumer Products Manufacturing,Manufacturing,$100 to $500 million (USD),"IMAGE Skincare, Aveda, Kiehl's",0,0
999,IT Data Engineer Associate,$98K-$180K (Glassdoor est.),**We are still hiring and interviewing for thi...,4.5,Global Atlantic Financial Group\n4.5,"New York, NY","New York, NY",1001 to 5000 employees,2004,Company - Private,Insurance Carriers,Insurance,Unknown / Non-Applicable,-1,0,0

In [54]:
df = df[df['Salary Estimate'] != '-1']
df.shape

(616, 16)

In [48]:
salary = df['Salary Estimate'].apply(lambda x: x.split('(')[0])
salary

0       $70K-$116K
1       $83K-$135K
4       $75K-$131K
5       $96K-$101K
6        $31K-$67K
           ...
994      $61K-$74K
995     $104K-$140K
996    $110K-$201K
998      $51K-$55K
999     $98K-$180K
Name: Salary Estimate, Length: 616, dtype: object

In [49]:
minus_Kd = salary.apply(lambda x: x.replace('K', '').replace('$', ''))
minus_Kd

0       70-116
1       83-135
4       75-131
5       96-101
6        31-67
         ...
994      61-74
995     104-140
996    110-201
998      51-55
999     98-180
Name: Salary Estimate, Length: 616, dtype: object

In [50]:
min_hr = minus_Kd.apply(lambda x: x.lower().replace('per hour','').replace('employer provided salary: ',''))
min_hr

0       70-116
1       83-135
4       75-131
5       96-101
6        31-67
         ...
994      61-74
995     104-140
996    110-201
998      51-55
999     98-180
Name: Salary Estimate, Length: 616, dtype: object

In [55]:
df = df.copy()
df['min_salary'] = min_hr.apply(lambda x: int(x.split('-')[0]))
df['max_salary'] = min_hr.apply(lambda x: int(x.split('-')[1]))
df['avg_salary'] = (df.min_salary+df.max_salary)/2
df

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly,employer_provided,min_salary,max_salary,avg_salary
0,Data Scientist,$70K-$116K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,0,0,70,116,93.0
1,Data Scientist,$83K-$135K (Glassdoor est.),"Data Scientist, Risk (4+ years of experience)\...",4.6,Turo\n4.6,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2009,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,-1,0,0,83,135,109.0
4,Data Scientist,$75K-$131K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,0,0,75,131,103.0
5,Data Scientist / Machine Learning Expert,$96K-$101K (Glassdoor est.),Posting Title\nData Scientist / Machine Learni...,3.9,Novartis\n3.9,"Cambridge, MA","Basel, Switzerland",10000+ employees,1996,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,96,101,98.5
6,Market Research Data Scientist,$31K-$67K (Glassdoor est.),"About Us\n\nAt GutCheck, we pioneered agile ma...",3.8,GutCheck\n3.8,"Denver, CO","Denver, CO",51 to 200 employees,2009,Company - Private,Advertising & Marketing,Business Services,$10 to $25 million (USD),"Nielsen, Zappi, SurveyMonkey",0,0,31,67,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,Big Data Engineer,$61K-$74K (Glassdoor est.),Company Profile:\n\nCaptiveAire is the nation'...,4.2,CaptiveAire\n4.2,"Raleigh, NC","Raleigh, NC",1001 to 5000 employees,1976,Company - Private,Industrial Manufacturing,Manufacturing,$100 to $500 million (USD),-1,0,0,61,74,67.5
995,"Senior Data Scientist, Product Development",$104K-$140K(Employer est.),Every immune system has a story to tell the ke...,4.0,Adaptive Biotechnologies\n4.0,"Seattle, WA","Seattle, WA",201 to 500 employees,2009,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1,0,0,104,140,122.0
996,"Senior Scientist, Analytical Sciences",$110K-$201K (Glassdoor est.),Forma Therapeutics is focused on the discovery...,4.0,FORMA THERAPEUTICS\n4.0,"Watertown, MA","Watertown, MA",51 to 200 employees,2008,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10 to $25 million (USD),-1,0,0,110,201,155.5
998,Data Analyst - Unilever Prestige,$51K-$55K (Glassdoor est.),Data Analyst - Unilever Prestige\nJob Code\n\n...,3.8,Dermalogica\n3.8,"Carson, CA","Carson, CA",201 to 500 employees,1986,Subsidiary or Business Segment,Consumer Products Manufacturing,Manufacturing,$100 to $500 million (USD),"IMAGE Skincare, Aveda, Kiehl's",0,0,51,55,53.0
999,IT Data Engineer Associate,$98K-$180K (Glassdoor est.),**We are still hiring and interviewing for thi...,4.5,Global Atlantic Financial Group\n4.5,"New York, NY","New York, NY",1001 to 5000 employees,2004,Company - Private,Insurance Carriers,Insurance,Unknown / Non-Applicable,-1,0,0,98,180,139.0

## company name text only
## state field
## age of company
## parsing of job description (python, etc.)